# Generated by Django 5.0.2 on 2024-02-13 20:38

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="category",
        ),
        migrations.AddField(
            model_name="job",
            name="company",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="job",
            name="expiration_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 14, 20, 38, 19, 53386, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="pub_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applicant_name", models.CharField(max_length=100)),
                ("applicant_email", models.EmailField(max_length=254)),
                ("resume", models.FileField(upload_to="resumes/")),
                ("cover_letter", models.TextField()),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.job"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
