# Generated by Django 5.0.1 on 2024-02-15 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_remove_application_cover_letter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="expiration_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 16, 14, 58, 23, 616940, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
